require:
  - rubocop-rails
  - rubocop-rspec
Layout/LineLength:
  Enabled: false
Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'