version: 2

jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.6.4-browsers
        environment:
          BUNDLER_VERSION: 2.0.2
    steps:
      - checkout

      - run:
          name: Docker Compose をインストール
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          name: コンテナを起動し、動作していることを検証
          command: |
            docker-compose up -d image_search elastic_search_test
            docker cp . project_image_search_1:/home/imagesearch
            docker-compose exec image_search bundle install
            docker-compose exec image_search bundle exec rspec --out /tmp/test-results/rspec.xml spec/models/meta_frame_spec.rb
            docker cp project_image_search_1:/tmp/test-results/rspec.xml /tmp/test-results/rspec.xml

      - store_test_results:
          path: /tmp/test-results/rspec.xml
#      - run:
#          command: |
#            echo $GCLOUD_SERVICE_KEY | tr -d ' ' | base64 --decode > vendor/gcs/googleapikey.json

#      - run:
#          command: |
#            curl -o wnjpn.db.gz http://compling.hss.ntu.edu.sg/wnja/data/1.1/wnjpn.db.gz
#            gzip -d wnjpn.db.gz
#            mv wnjpn.db db/wnjpn.sqlite3

#      - store_artifacts:
#          path: ~/rspec
#
#      - store_artifacts:
#          path: ~/project/tmp/screenshots
#


workflows:
  version: 2
  test:
    jobs:
      - rspec